apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: master
        image: lucasfdutra/flask-hello:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
    name: flask-hello-service
spec:
    selector:
      app: flask-hello
    ports:
    - port: 5000
      targetPort: 5000